### ISSUE TITLE
Dependabot not checking versions properly

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android-common#21]
As outlined in https://github.com/nextcloud/android-common/pull/20 and https://github.com/dependabot/dependabot-core/issues/3286, dependabot does not respect the repositories defined in `settings.gradle` and instead uses some default repos (jcenter, maven central, and plugins.gradle.org), which means dependencies from google's maven repo are never updated. Check [this run](https://github.com/nextcloud/android-common/network/updates/484443712) for example.

Alternatives to get automated version updates right now:
1. Move to the old way of defining repos in `repositories` blocks at script level. 
2. Try using renovatebot instead of dependabot. It's more maintained at least, and this usecase _should_ work.

This is not urgent as this repo does not have that many dependencies, but as it grows it will become worse.

**Comment by tobiasKaminsky** [comment]
Strange that this is not requested more often, as dependabot is now default on GitHub and there are lots of Android repositories…

**Comment by AlvaroBrey** [comment]
If we get Renovate working on the config repo and it works well (https://github.com/nextcloud/android-config/pull/22/files), we may want to use it here as well for Gradle. That  may fix this issue.

**Comment by AndyScherzinger** [comment]
implemented renovate via https://github.com/nextcloud/android-common/pull/251
