### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/android-common#302]
Hi everyone,

all code has been licensed under GPL3+ accidentially. Accidentially because we want to have any Android library published under MIT while the apps we build are licensed under GPL3+. Hence this issues here. So in order to change the license it needs an approval of all contributors in oder to change the license of the code you contributed.

Hence pinging
- @AndyScherzinger ✅ 
- @tobiasKaminsky ✅ 
- @Unpublished ✅ 
- @thgoebel ✅ 
- @stefan-niedermann ✅ 
- @AlvaroBrey ✅ 

A short comment that you are fine with the change is enough. Theoretically an approval by @tobiasKaminsky @AlvaroBrey might not be needed since these contributions happened as Nextcloud employees. But I looped yo in anyways.

**Comment by AndyScherzinger** [comment]
I approve of the license change


...obviously

**Comment by thgoebel** [comment]
I approve the change to MIT.

Though I want to add that a lot of the Android ecosystem (AOSP, androidx, Material Components, Square’s okhttp, …) is licensed under Apache-2.0. So if you want to align with the ecosystem, maybe use Apache rather than MIT. I approve a change to Apache 2.0, too.

**Comment by stefan-niedermann** [comment]
I do not want to be the bottleneck, I also agree.

However as a strong supporter of copyleft licenses I'd like to ask for the reason :)

**Comment by AndyScherzinger** [comment]
> However as a strong supporter of copyleft licenses I'd like to ask for the reason :)

No strong reason, rather the thought of having a bit more flexibility choosing a license as a app developer when utilizing this lib (same question for changing the license would need to be asked for the SSO lib btw.)

So yeah, we could stick to GPL3+, but any app using `android-common` would basically have to choose the same license explicitly or implicitly (by using this lib). For the files app for example it means that the MIT-licensed `android-library` gets overwritten license-wise by the app's GPL3+. Hence the idea to license the libs under MIT rather than GPL.

Any particular reason you think the GPL3+ could be the better choice @stefan-niedermann - also just asking out of curiosity.

**Comment by stefan-niedermann** [comment]
> any app using android-common would basically have to choose the same license explicitly or implicitly (by using this lib).

I do not think that this is true. What you described is what matters when one makes adjustments on and redistributes the lib itself (for example within an third party app).

Noone is forced to distribute an app that *uses* the lib without any modifications under GPL.

(No warranty, that's what I believe)

**Comment by AlvaroBrey** [comment]
Just here to say that I am okay with changing the license to either MIT or Apache (as discussed above).

> Noone is forced to distribute an app that uses the lib without any modifications under GPL.

Yes, yes they are. Distributing an app that uses the lib (and therefore contains compiled code from the lib) counts as redistribution and is bound by the GPL. The only exception to this would be if you're serving the output of your software over the network (which is why AGPL exists).

**Comment by stefan-niedermann** [comment]
> Distributing an app that uses the lib (and therefore contains code from the lib) counts as redistribution 

Interesting, thank you for the information, I have done some research about this topic and I have fixed my opinion about GPL library usage.

Not enforcing third party apps being licensed under GPL looks a bit like a game changer for the ecosystem. Might make the way to proprietary and / or paid apps on apps.nextcloud.com in the long term (no judgment).

**Comment by AndyScherzinger** [comment]
> Not enforcing third party apps being licensed under GPL looks a bit like a game changer for the ecosystem. Might make the way to proprietary and / or paid apps on apps.nextcloud.com in the long term (no judgment).

@stefan-niedermann Just to be clear we are just talking about the Android libs here - nothing else. So the apps on the server-side are always AGPL by design. They are written in PHP, get executed in the same thread, hence always AGPL because the underlying platform is AGPL.

**Comment by stefan-niedermann** [comment]
Yep, I got that :)

**Comment by AndyScherzinger** [comment]
> Might make the way to proprietary and / or paid apps on apps.nextcloud.com in the long term (no judgment).

@stefan-niedermann Well the comment was about this statement ;) ...which isn't possible in any way due to the nature of PHP (single thread execution)

**Comment by tobiasKaminsky** [comment]
Fine by me :+1:
