### ISSUE TITLE
stale bot not working on Talk

### ISSUE THREAD

**Issue by AlvaroBrey** [nextcloud/android-common#8]
Files/library use the `needs info/discussion` label to mark stale-able issues. This is the label that the stale workflow filters for.

However, Talk uses just `needs info`, and it's not picked up by the stale bot.

To fix this we have two options:

a) Change the workflow so it accepts either `needs info` or `needs info/discussion`
b) Change the labels so all three repos use the same one. 

I prefer b), and would use just `needs info` in all three. 
cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
b) is fine by me.
Renaming should not cause any harm 👍

**Comment by AlvaroBrey** [comment]
> b) is fine by me. Renaming should not cause any harm +1

Renamed the tags in Files and library. PR to update workflow in #9
